name: SaveStats
version: ${project.version}
main: me.minemis.savestats.SaveStats
author: minemis
api-version: 1.12.2
commands:
  showtime:
    description: Shows how much time has passed since Player logged in.
    usage: /showtime
  totaltime:
    description: Show total player played time
    usage: /totaltime
  resetServerData:
    description: Resets all data saved in data.json. Fresh new server!
    usage: /resetserverdata